# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-p9sDSw9uShnQvA-UjfWTWrWxDXz1pbq
"""

from keras.models import Sequential
from keras.layers import Dense, Flatten, Dropout, Input
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import to_categorical
from tensorflow.keras.preprocessing.image import ImageDataGenerator # Corrected import path

train_dir="/content/drive/MyDrive/food"
img_width,img_height=200,200
batch_size=32
train_datagen=ImageDataGenerator(rescale=1./255,
                                 rotation_range=30,
                                 width_shift_range=0.2,
                                 height_shift_range=0.2,
                                shear_range=0.2,
                                zoom_range=0.2,
                                horizontal_flip=True,
                                 fill_mode='nearest')
train_generator=train_datagen.flow_from_directory(train_dir,
                                                  target_size=(img_width,img_height),
                                                  batch_size=batch_size,
                                                  class_mode='categorical')

img_width, img_height = 200, 200
model = Sequential([
    Input(shape=(img_width, img_height, 3)),
    Conv2D(32, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(5, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()
epochs=150
history = model.fit(train_generator, epochs=epochs)

model.save('food.h5')

from keras.utils import load_img
import numpy as np
import matplotlib.pyplot as plt
path = "/content/bunbo.jpg"
img = load_img(path, target_size=(200, 200))
plt.imshow(img)
plt.show()
img=np.array(img)
img=img/255
img=img.reshape(1,200,200,3)
preds = model.predict(img)
prediction = np.argmax(preds)
confidence = preds[0][prediction] * 100
class_labels = {v: k for k, v in train_generator.class_indices.items()}
food_pred = class_labels[prediction]
print(f"Món ăn dự đoán: {food_pred}")

